base_url = "https://maltsev-dev.github.io"
title = "dev_stories"
theme = "terminimal"
compile_sass = true

taxonomies = [{ name = "tags" }]

#build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
accent_color = "orange"
logo_text = "busy hands == happy heart"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

copyright_html = """
<div class="copyright">
    <span>Â© 2025 A.Maltsev</span>
    <span class="copyright-theme-sep"> | </span>
    <span><img src="https://visitor-badge.laobi.icu/badge?page_id=maltsev-dev.github.io&right_color=orange" alt="Visitors"></span>
</div>
"""
author = "maltsev-dev"
menu_items = [
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "rust", url = "$BASE_URL/tags/rust/" },
    { name = "embedded", url = "$BASE_URL/tags/embedded/" },
    { name = "projects", url = "$BASE_URL/tags/project/" },
    { name = "about", url = "$BASE_URL/about" },
    { name = "cv.pdf", url = "https://github.com/maltsev-dev/maltsev-dev.github.io/raw/main/static/CV_Anatoly_Maltsev.pdf", newtab = true },
]

enable_post_view_navigation = false
post_view_navigation_prompt = "Read other posts?"
use_full_font = true
favicon = "/favicon.png"
favicon_mimetype = "image/png"
page_titles = "combined"
